name: sh_toast
description: "A Flutter package for displaying toast notifications on all platforms."
version: 2.0.1
homepage: https://procodersc.blogspot.com

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

example:
  main.dart


dependencies:
  flutter:
    sdk: flutter

flutter:
  
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
